version: "3.7"

services:
  db_vuc:
    container_name: postgres_container
    image: postgres
    environment:
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379
    env_file:
      - .env
    restart: unless-stopped

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "8080:8000"
    depends_on:
      - db_vuc
      - redis
    restart: unless-stopped

  celery:
    build:
      context: .
    env_file:
      - .env
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis
    restart: unless-stopped

  flower:
    build:
      context: .
    env_file:
      - .env
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - "8888:5555"
    restart: unless-stopped
