version: "3.7"

services:
  db_vuc:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_PASSWORD:-vuc}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 8888:8000
    depends_on:
      - db_vuc
      - redis
