"""added discipline table

Revision ID: f95ccf8ffcae
Revises: 68503d2c2922
Create Date: 2024-04-18 19:45:08.971422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f95ccf8ffcae"
down_revision: Union[str, None] = "68503d2c2922"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("encouragement", "penalty", name="_type").create(op.get_bind())
    op.create_table(
        "discipline",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "encouragement", "penalty", name="_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "comment",
            sa.String().with_variant(sa.String(length=255), "postgresql"),
            nullable=False,
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("discipline")
    sa.Enum("encouragement", "penalty", name="_type").drop(op.get_bind())
    # ### end Alembic commands ###
