"""rename column platoon_id to platoon_number in student

Revision ID: 49902239bb3e
Revises: e1be06a11531
Create Date: 2024-03-03 22:37:18.207798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49902239bb3e"
down_revision: Union[str, None] = "e1be06a11531"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student", sa.Column("platoon_number", sa.Integer(), nullable=False)
    )
    op.drop_column("student", "platoon_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student",
        sa.Column(
            "platoon_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("student", "platoon_number")
    # ### end Alembic commands ###
