"""add view platoons

Revision ID: 98b3986e8ae6
Revises: f657ce76a7ee
Create Date: 2024-02-23 19:09:29.857097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from models.view.platoons import Platoons

# revision identifiers, used by Alembic.
revision: str = '98b3986e8ae6'
down_revision: Union[str, None] = 'f657ce76a7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Platoons.create(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Platoons.create(op)
    # ### end Alembic commands ###
