"""new type for role in users

Revision ID: b948b7addada
Revises: 027abfdf55d3
Create Date: 2024-02-24 17:05:47.236426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b948b7addada'
down_revision: Union[str, None] = '027abfdf55d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Student', 'PlatoonCommander', 'SquadCommander', 'Professor', 'Admin', name='rolesrange').create(op.get_bind())
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Student', 'PlatoonCommander', 'SquadCommander', 'Professor', 'Admin', name='rolesrange'),
               existing_nullable=False,
               postgresql_using='role::rolesrange')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Enum('Student', 'PlatoonCommander', 'SquadCommander', 'Professor', 'Admin', name='rolesrange'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    sa.Enum('Student', 'PlatoonCommander', 'SquadCommander', 'Professor', 'Admin', name='rolesrange').drop(op.get_bind())
    # ### end Alembic commands ###
