"""try add view attendance to db

Revision ID: b91906e0c9e9
Revises: 6efb108822da
Create Date: 2024-02-23 16:22:42.667107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.view.attendance import Attendance


# revision identifiers, used by Alembic.
revision: str = 'b91906e0c9e9'
down_revision: Union[str, None] = '6efb108822da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Attendance.create(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Attendance.drop(op)
    # ### end Alembic commands ###
