"""refactor view marks and attendance

Revision ID: e550fa2eae53
Revises: 01a15af02665
Create Date: 2024-02-23 17:33:12.087809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from models.view.attendance import Attendance
from models.view.marks import Marks

# revision identifiers, used by Alembic.
revision: str = 'e550fa2eae53'
down_revision: Union[str, None] = '01a15af02665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Marks.create(op)
    Attendance.create(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Marks.drop(op)
    Attendance.drop(op)
    # ### end Alembic commands ###
