"""init views 

Revision ID: cf8719f80d7a
Revises: f7da5b70c3b8
Create Date: 2024-03-03 23:35:16.615096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from models.view.attendance import Attendance
from models.view.marks import Marks
from models.view.platoons import Platoons
from models.view.students import Students
from models.view.users import Users

# revision identifiers, used by Alembic.
revision: str = "cf8719f80d7a"
down_revision: Union[str, None] = "f7da5b70c3b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Attendance.create(op)
    Marks.create(op)
    Platoons.create(op)
    Students.create(op)
    Users.create(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Attendance.drop(op)
    Marks.drop(op)
    Platoons.drop(op)
    Students.drop(op)
    Users.drop(op)
    # ### end Alembic commands ###
