"""rename students table to student

Revision ID: a6d39f3a73ac
Revises: e550fa2eae53
Create Date: 2024-02-23 17:53:29.909871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d39f3a73ac'
down_revision: Union[str, None] = 'e550fa2eae53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('institute', sa.String(), nullable=True),
    sa.Column('direction_of_study', sa.String(), nullable=True),
    sa.Column('group_study', sa.String(), nullable=True),
    sa.Column('platoon_number', sa.Integer(), nullable=True),
    sa.Column('vus', sa.Integer(), nullable=True),
    sa.Column('squad_number', sa.Integer(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('institute', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('direction_of_study', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_study', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platoon_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('squad_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='students_pkey')
    )
    op.drop_table('student')
    # ### end Alembic commands ###
