"""replace syntax sqla 1 to sqla 2

Revision ID: 7819f8005bcc
Revises: 98b3986e8ae6
Create Date: 2024-02-24 16:23:04.529901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7819f8005bcc'
down_revision: Union[str, None] = '98b3986e8ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'mail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'institute',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'direction_of_study',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'platoon_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'squad_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'group_study',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'group_study',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'squad_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'platoon_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'direction_of_study',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'institute',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'mail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
