"""drop some view

Revision ID: 027abfdf55d3
Revises: a866ee042f74
Create Date: 2024-02-24 17:00:55.439623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.view.attendance import Attendance
from src.models.view.marks import Marks
from src.models.view.platoons import Platoons
from src.models.view.students import Students
from src.models.view.users import Users


# revision identifiers, used by Alembic.
revision: str = '027abfdf55d3'
down_revision: Union[str, None] = 'a866ee042f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Attendance.drop(op)
    Marks.drop(op)
    Platoons.drop(op)
    Students.drop(op)
    Users.drop(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Attendance.create(op)
    Marks.create(op)
    Platoons.create(op)
    Students.create(op)
    Users.create(op)
    # ### end Alembic commands ###
