"""New constraint in User table

Revision ID: 6df322921ecc
Revises: 5d0f2a024ee8
Create Date: 2024-02-26 18:17:01.374826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6df322921ecc'
down_revision: Union[str, None] = '5d0f2a024ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('squad_number_check_c',
                               'user',
                               'squad_number IN (1, 2, 3)',
                               )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('squad_number_check_c', 'user')
    # ### end Alembic commands ###
