"""revision init

Revision ID: 327ba1e84c53
Revises: 
Create Date: 2024-02-16 20:06:46.051722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '327ba1e84c53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platoon')
    op.drop_table('professor')
    op.drop_table('students')
    op.drop_table('attendance')
    op.drop_table('tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('telegram_id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint("ARRAY[role] <@ ARRAY['Студент'::text, 'Командир взвода'::text, 'Командир отделения'::text, 'Admin'::text]", name='role_check'),
    sa.PrimaryKeyConstraint('token', name='tokens_pkey'),
    sa.UniqueConstraint('telegram_id_user', name='telegram_id_unique')
    )
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_v', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('visiting', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='attendance_pkey')
    )
    op.create_table('students',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date_of_brith', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mail', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('institute', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('direction_of_study', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('group_study', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('course_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vus', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platoon_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('squad_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint("ARRAY[role] <@ ARRAY['Студент'::text, 'Командир взвода'::text, 'Командир отделения'::text, 'Admin'::text]", name='role_check'),
    sa.PrimaryKeyConstraint('telegram_id', name='students_pkey')
    )
    op.create_table('professor',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('platoons', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', name='telegram_id')
    )
    op.create_table('platoon',
    sa.Column('platoon_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_t_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('student_t_id', name='platoon_pkey')
    )
    # ### end Alembic commands ###
