"""convert all table from sqla 1 style to sqla 2 style

Revision ID: a866ee042f74
Revises: 7819f8005bcc
Create Date: 2024-02-24 16:34:41.207544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a866ee042f74'
down_revision: Union[str, None] = '7819f8005bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('admins', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('admins', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('attend', 'visiting',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attend', 'semester',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grading', 'theme',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('student', 'mail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'institute',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'direction_of_study',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'group_study',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'platoon_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student', 'vus',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student', 'squad_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student', 'squad_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student', 'vus',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student', 'platoon_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student', 'group_study',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'direction_of_study',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'institute',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'mail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('student', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grading', 'theme',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attend', 'semester',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attend', 'visiting',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('admins', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('admins', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('admins', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
