"""new type of role column in user table

Revision ID: 3ac901ac35db
Revises: 2e877ced0537
Create Date: 2024-02-24 19:01:22.621045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ac901ac35db'
down_revision: Union[str, None] = '2e877ced0537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('Student', 'PlatoonCommander', 'SquadCommander', 'Professor', 'Admin', name='rolesrange'),
               type_=sa.String(),
               existing_nullable=False)
    sa.Enum('Student', 'PlatoonCommander', 'SquadCommander', 'Professor', 'Admin', name='rolesrange').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Student', 'PlatoonCommander', 'SquadCommander', 'Professor', 'Admin', name='rolesrange').create(op.get_bind())
    op.alter_column('user', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('Student', 'PlatoonCommander', 'SquadCommander', 'Professor', 'Admin', name='rolesrange'),
               existing_nullable=False)
    # ### end Alembic commands ###
